export type Product = {
  id: number;
  name: string;
  brand: string;
  brandSlug: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  tag?: "Sale" | "New" | "Hit";
  sizes: number[];
};

// Реальные фото моделей, скачаны в /public/products (источник: Wikimedia Commons, CC).
export const products: Product[] = [
  {
    id: 1,
    name: "Triple S",
    brand: "Balenciaga",
    brandSlug: "balenciaga",
    price: 1090,
    oldPrice: 1350,
    rating: 4.9,
    reviews: 342,
    image: "/products/balenciaga-triple-s.jpg",
    tag: "Sale",
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 2,
    name: "Air Jordan 4 Cement",
    brand: "Nike",
    brandSlug: "nike",
    price: 420,
    rating: 5.0,
    reviews: 528,
    image: "/products/jordan-4-cement.jpg",
    tag: "Hit",
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 3,
    name: "SB Dunk Low Pro",
    brand: "Nike",
    brandSlug: "nike",
    price: 180,
    rating: 4.8,
    reviews: 412,
    image: "/products/nike-sb-dunk-low.jpg",
    sizes: [39, 40, 41, 42, 43, 44, 45],
  },
  {
    id: 4,
    name: "Samba OG",
    brand: "adidas",
    brandSlug: "adidas",
    price: 130,
    rating: 4.7,
    reviews: 894,
    image: "/products/adidas-samba.jpg",
    tag: "Hit",
    sizes: [38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: 5,
    name: "Air Max 90",
    brand: "Nike",
    brandSlug: "nike",
    price: 150,
    oldPrice: 190,
    rating: 4.8,
    reviews: 367,
    image: "/products/nike-air-max-90.jpg",
    tag: "Sale",
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 6,
    name: "Yeezy Boost 350 V2 Onyx",
    brand: "adidas Yeezy",
    brandSlug: "yeezy",
    price: 300,
    rating: 4.9,
    reviews: 256,
    image: "/products/yeezy-350-onyx.jpg",
    tag: "New",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: 7,
    name: "Yeezy Boost 350 V2 Sesame",
    brand: "adidas Yeezy",
    brandSlug: "yeezy",
    price: 280,
    rating: 4.8,
    reviews: 198,
    image: "/products/yeezy-350-sesame.jpg",
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 8,
    name: "550",
    brand: "New Balance",
    brandSlug: "new-balance",
    price: 140,
    rating: 4.7,
    reviews: 321,
    image: "/products/new-balance-550.jpg",
    tag: "Hit",
    sizes: [39, 40, 41, 42, 43, 44],
  },
  {
    id: 9,
    name: "990v5",
    brand: "New Balance",
    brandSlug: "new-balance",
    price: 200,
    rating: 4.9,
    reviews: 176,
    image: "/products/new-balance-990.jpg",
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 10,
    name: "Air Jordan 1 Retro High OG",
    brand: "Nike",
    brandSlug: "nike",
    price: 390,
    oldPrice: 470,
    rating: 5.0,
    reviews: 643,
    image: "/products/jordan-1-silver.jpg",
    tag: "Sale",
    sizes: [40, 41, 42, 43, 44, 45],
  },
  {
    id: 11,
    name: "Air Force 1 Hi Just Don",
    brand: "Nike",
    brandSlug: "nike",
    price: 250,
    rating: 4.6,
    reviews: 142,
    image: "/products/nike-af1-just-don.jpg",
    tag: "New",
    sizes: [40, 41, 42, 43, 44],
  },
  {
    id: 12,
    name: "Samba Originals",
    brand: "adidas",
    brandSlug: "adidas",
    price: 120,
    rating: 4.7,
    reviews: 405,
    image: "/products/adidas-samba-2.jpg",
    sizes: [38, 39, 40, 41, 42, 43, 44],
  },
];
